service: your-service-name

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: main.handler # Replace 'app' with the name of your Python file containing the FastAPI app and Mangum handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any
